name: Cross-build ungoogled-chromium

on:
  workflow_dispatch:
    inputs:
      container_image:
        description: "Build in container image"
        default: chromium-win-cross:latest

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone u-c-w Git repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 50
          fetch-tags: true
