name: Cross-build ungoogled-chromium

on:
  workflow_dispatch:
    inputs:
      container_image:
        description: "Build in container image"
        default: chromium-win-cross:latest

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
      - name: Get lead runner info
        run: |
          address=$(hostname -i)
          ssh_hkey=$(cat /etc/ssh/ssh_host_ed25519_key.pub)
          echo "Runner IP address: $address"
          echo "Runner SSH hostkey: $ssh_hkey"
          (echo "LEADER_ADDRESS=$address"
           echo "LEADER_SSH_HOSTKEY=$ssh_hkey"
          ) > leader-info.env
      - name: XXX
        uses: actions/upload-artifact@v4
        with:
          name: leader-info
          path: leader-info.env
          if-no-files-found: error
          retention-days: 1
      - name: XXX2
        run: |
          set -x
          sudo iptables -F || echo failed
          sudo nft flush ruleset || echo failed
      - name: Clone u-c-w Git repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 50
          fetch-tags: true
      - name: Get Chromium version info
        id: version
        run: |
          version=$(cat ungoogled-chromium/chromium_version.txt)
          echo "Chromium version: $version"
          echo "chromium=$version" >> $GITHUB_OUTPUT
      - name: Restore Chromium source tarball download cache
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          key: chromium-source-${{steps.version.outputs.chromium}}
          path: cross-build/build/download_cache
      - name: Download and/or verify Chromium source tarball
        run: |
          cache=cross-build/build/download_cache
          mkdir -p $cache
          ungoogled-chromium/utils/downloads.py retrieve \
            --ini ungoogled-chromium/downloads.ini \
            --cache $cache
          ls -l $cache
      - name: Save Chromium source tarball download cache
        if: ${{!steps.restore-cache.outputs.cache-hit}}
        uses: actions/cache/save@v4
        with:
          key: chromium-source-${{steps.version.outputs.chromium}}
          path: cross-build/build/download_cache
      - name: Download cross-build container
        run: |
          echo ${{secrets.GHCR_TOKEN}} | docker login ghcr.io --username ${{github.actor}} --password-stdin
          docker pull ghcr.io/${{github.repository_owner}}/${{github.event.inputs.container_image}}
          docker logout ghcr.io
      - name: Free up some disk space on the runner
        run: |
          echo Before:
          df -m .
          sudo rm -rf \
            /usr/local/.ghcup \
            /usr/local/lib/android \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/swift \
            "$AGENT_TOOLSDIRECTORY"
          echo After:
          df -m .
      - name: Run build inside container
        run: |
          docker container run --rm \
            --name=chromium-win-cross-con \
            --hostname=chromium-win-cross-con \
            --volume $PWD:/home/build/u-c-w \
            ghcr.io/${{github.repository_owner}}/${{github.event.inputs.container_image}} \
            sh -c 'cd u-c-w/cross-build && ./build.sh --ci'
      - name: Archive build outputs
        uses: actions/upload-artifact@v4
        with:
          name: packages
          compression-level: 9
          path: cross-build/build/ungoogled-chromium_*
      # TODO: Delete leader-info artifact



  helper-1:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
      - name: XXX
        uses: actions/download-artifact@v4
        with:
          name: leader-info
      - name: YYY
        run: cat leader-info.env >> $GITHUB_ENV
      - run: |
          set -x
          hostname -i
          sudo iptables -F || echo failed
          sudo nft flush ruleset || echo failed
          ####
          mkdir --mode=700 ~/.ssh
          echo "$LEADER_ADDRESS $LEADER_SSH_HOSTKEY" > ~/.ssh/known_hosts
          tracepath $LEADER_ADDRESS
          ping -c 10 -W 10 $LEADER_ADDRESS || true
          ping -c 10 -W 10 www.netscape.com || true
          ssh -o BatchMode=yes $LEADER_ADDRESS uptime


# EOF
